name: Jumptube

on:
  schedule:
    - cron: '0 */5 * * *'  # every 5 hours
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 330  # 5 hours 30 mins
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js and Playwright
      - name: Setup Node.js and Playwright
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g playwright
          npx playwright install firefox

      # Step 3: Install unzip and Xvfb
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb

      # Step 4: Run Jumptube-1
      - name: Run Jumptube-1
        run: |
          unzip -o firefox-profile-1.zip -d ./firefox-profile-1
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node jumptube-1.js
        continue-on-error: true

      # Step 5: Run Jumptube-2
      - name: Run Jumptube-2
        run: |
          unzip -o firefox-profile-2.zip -d ./firefox-profile-2
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node jumptube-2.js
        continue-on-error: true

      # Step 6: Run Jumptube-3
      - name: Run Jumptube-3
        run: |
          unzip -o firefox-profile-3.zip -d ./firefox-profile-3
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node jumptube-3.js
        continue-on-error: true
