name: Jumptube

on:
  schedule:
    - cron: '0 */5 * * *'  # every 5 hours
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 330

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install Playwright locally in the runner
      - name: Setup Playwright locally
        run: |
          npm init -y
          npm install playwright
          npx playwright install firefox
          sudo apt-get update
          sudo apt-get install -y unzip xvfb

      # Unzip all Firefox profiles
      - name: Unzip Firefox profiles
        run: |
          unzip -o firefox-profile-1.zip -d ./firefox-profile-1
          unzip -o firefox-profile-2.zip -d ./firefox-profile-2
          unzip -o firefox-profile-3.zip -d ./firefox-profile-3

      # Run Jumptube-1
      - name: Run Jumptube-1
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" node jumptube-1.js
        continue-on-error: true

      # Upload screenshot
      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: jumptask-screenshot
          path: page_debug.png
